global:
  scrape_interval: 15s

scrape_configs:
  # --- Renommez le job ici ---
  - job_name: 'prometheus' # Ancien nom: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          app: 'rest-benchmark'
